name: Build initrd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download Utils
      run: sudo apt-get install binutils gmp mpfr libmpc gcc-4.8
    - name: Dockerlize
      run: ./docker-build.sh
    - name: ls
      run: ls
